#!/bin/bash

# Auto-Build Environment Setup for TypeScript + React + Redux Migration
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Project: Notepad TypeScript Migration"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# DEPENDENCY CHECK
# ============================================

echo ""
echo "Checking dependencies..."

# Check if TypeScript is installed
if npm list typescript &>/dev/null; then
    echo -e "${GREEN}✓ TypeScript installed${NC}"
else
    echo -e "${YELLOW}! TypeScript not found - will be installed by subtasks${NC}"
fi

# Check if React is installed
if npm list react &>/dev/null; then
    echo -e "${GREEN}✓ React installed${NC}"
else
    echo -e "${YELLOW}! React not found - will be installed by subtasks${NC}"
fi

# Check if Redux Toolkit is installed
if npm list @reduxjs/toolkit &>/dev/null; then
    echo -e "${GREEN}✓ Redux Toolkit installed${NC}"
else
    echo -e "${YELLOW}! Redux Toolkit not found - will be installed by subtasks${NC}"
fi

# ============================================
# START BROWSER DEV SERVER
# ============================================

echo ""
echo "Starting browser development server..."
echo "Note: This will fail until TypeScript/React are set up"
echo "After dependencies are installed, run: npm run dev:browser"

# Uncomment this after Phase 1 completes:
# npm run dev:browser &
# wait_for_service 5173 "Browser Dev Server"

# ============================================
# ELECTRON APP (Optional)
# ============================================

# Uncomment this to launch Electron after implementation:
# echo ""
# echo "Starting Electron app..."
# npm run dev:electron &

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Setup Instructions"
echo "========================================"
echo ""
echo "This is a TypeScript + React + Redux migration."
echo ""
echo "Initial Setup (Phase 1):"
echo "  1. Install dependencies (run implementation subtasks 1-1 to 1-3)"
echo "  2. Create TypeScript configs (subtasks 1-4 to 1-7)"
echo ""
echo "Development Workflow:"
echo "  - Browser version: npm run dev:browser (port 5173)"
echo "  - Electron version: npm run dev:electron"
echo "  - Build browser: npm run build:browser"
echo "  - Build Electron: npm run build:electron"
echo ""
echo "Implementation Progress:"
echo "  Follow implementation_plan.json"
echo "  - Phase 1: Setup & Config"
echo "  - Phase 2: Redux Infrastructure"
echo "  - Phase 3: Shared Utilities → TypeScript"
echo "  - Phase 4: React Components"
echo "  - Phase 5: Browser Integration"
echo "  - Phase 6: Electron Integration"
echo "  - Phase 7: Integration & Verification"
echo ""
echo "Current state: Dependencies NOT installed yet"
echo "Run Phase 1 subtasks to begin migration."
echo ""
