#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 003: macOS Installation Package Configuration

set -e

echo "========================================"
echo "macOS Package Build Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check if on macOS (for building macOS packages)
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo -e "${GREEN}✓ Running on macOS - native builds supported${NC}"
else
    echo -e "${YELLOW}⚠ Not running on macOS - will need Docker/CI for macOS builds${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ -f "package.json" ]; then
    # Check if node_modules exists and is up to date
    if [ ! -d "node_modules" ] || [ "package.json" -nt "node_modules" ]; then
        echo "Running npm install..."
        npm install
        echo -e "${GREEN}✓ Dependencies installed${NC}"
    else
        echo -e "${GREEN}✓ Dependencies already up to date${NC}"
    fi
else
    echo -e "${RED}Error: package.json not found${NC}"
    exit 1
fi

# ============================================
# VERIFY ELECTRON-BUILDER
# ============================================

echo ""
echo "Verifying electron-builder installation..."

if npm list electron-builder --depth=0 &> /dev/null; then
    ELECTRON_BUILDER_VERSION=$(npm list electron-builder --depth=0 | grep electron-builder | sed 's/.*@//')
    echo -e "${GREEN}✓ electron-builder ${ELECTRON_BUILDER_VERSION}${NC}"
else
    echo -e "${RED}Error: electron-builder is not installed${NC}"
    exit 1
fi

# ============================================
# WORKSPACE INFO
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: Notepad Electron App"
echo "Spec: 003 - macOS Installation Package Configuration"
echo "Working Directory: $(pwd)"
echo ""
echo "This task will:"
echo "  - Create electron-builder.yml configuration"
echo "  - Set up macOS entitlements for code signing"
echo "  - Configure DMG and PKG installer targets"
echo "  - Add build scripts to package.json"
echo "  - Create build documentation"
echo ""
echo "Implementation will create:"
echo "  - build/ directory for assets (icon, entitlements)"
echo "  - docs/ directory for BUILDING.md"
echo "  - electron-builder.yml (main config)"
echo "  - .env.example (code signing template)"
echo ""
echo -e "${YELLOW}Note: This is a planning workspace. Implementation will happen in next session.${NC}"
echo ""
echo "Ready to begin planning!"
echo ""
