#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Dual-Platform Notepad Application

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/alexanderfedin/Projects/hapyy/playground/notepad"
cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PREREQUISITE CHECKS
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if package.json exists
if [ ! -f "package.json" ]; then
    echo -e "${YELLOW}Warning: package.json not found. Run implementation first.${NC}"
    exit 1
fi

# Check if dependencies are installed
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing npm dependencies...${NC}"
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."
echo ""

# Option 1: Start Browser Dev Server
echo -e "${GREEN}Option 1: Browser Mode${NC}"
echo "  Command: npm run dev:browser"
echo "  URL: http://localhost:5173"
echo ""

# Option 2: Start Electron
echo -e "${GREEN}Option 2: Electron Desktop Mode${NC}"
echo "  Command: npm run dev:electron"
echo ""

# Ask user which mode to start
read -p "Which mode do you want to start? (b=browser, e=electron, both): " mode

case $mode in
    b|B|browser)
        echo ""
        echo "Starting browser dev server..."
        npm run dev:browser
        ;;
    e|E|electron)
        echo ""
        echo "Starting Electron app..."
        npm run dev:electron
        ;;
    both)
        echo ""
        echo "Starting both browser and Electron..."
        echo "Browser server will start first, then Electron will launch..."
        npm run dev:browser &
        BROWSER_PID=$!
        wait_for_service 5173 "Browser Dev Server"
        npm run dev:electron &
        ELECTRON_PID=$!
        echo ""
        echo -e "${GREEN}Both services started!${NC}"
        echo "  Browser: http://localhost:5173"
        echo "  Electron: Desktop window should be open"
        echo ""
        echo "Press Ctrl+C to stop all services"
        wait
        ;;
    *)
        echo -e "${RED}Invalid option. Please run again and choose 'b', 'e', or 'both'.${NC}"
        exit 1
        ;;
esac

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Development Modes:"
echo "  Browser:  npm run dev:browser  (http://localhost:5173)"
echo "  Electron: npm run dev:electron (desktop app)"
echo ""
echo "File Structure:"
echo "  src/shared/        - Shared code (editor, file system abstraction)"
echo "  src/browser/       - Browser-specific implementation"
echo "  src/electron/      - Electron-specific implementation"
echo "  public/            - Static assets (CSS, themes)"
echo ""
echo "Testing:"
echo "  Unit tests:        npm test"
echo "  Browser test:      Open http://localhost:5173 in Chrome/Edge"
echo "  Electron test:     Launch desktop app and test file operations"
echo ""
